sonar.projectKey=Nimesh-Capstone-Project_Parking-System-AuthService_38163bf1-a4fc-44fd-8116-772f4ea206f6

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.js,**/*.spec.js,**/*.test.ts,**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/**,coverage/**,dist/**,build/**